; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; Airbrakes flying seal: /dev/cu.usbserial-AU0K3FHU
; On sled flying seal: /dev/cu.usbserial-AU0K4AAD

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
lib_deps =
	sparkfun/SparkFun BNO080 Cortex Based IMU@^1.1.12
	
	
	
